kraken-tech/django-pg-migration-tools

docs/index.rst

This has been a ctrl+c/ctrl+v oversight. We all love the extended mypy plug in but that's not quite like we're installing here!

Add the correct installation lib

---

README.md
docs/index.rst
docs/usage/management_commands.rst
docs/usage/operations.rst
docs/usage/timeouts.rst

A few minor change suggestions to the docs, mainly nitpicks. Feel free use what you want. (Sorry I haven't broken the commits more granularly.)

Docs tweaks 20240815

---

CHANGELOG.md
docs/usage/operations.rst
pyproject.toml
src/django_pg_migration_tools/operations.py
tests/django_pg_migration_tools/test_operations.py

Prior to this change, we weren't checking if the database router allowed the migration to proceed.
We thus add the router.allow_migrate() check, which is the same that the RunSQL operation runs internally. Ref:
- https://github.com/django/django/blob/7adb6dd98d50a238f3eca8c15b16b5aec12575fd/django/db/migrations/operations/special.py#L105
A possible error that would raise before this fix happens when the Django applicatoin has multiple databases and the migration should be routed to only apply on a particular database.

Do not migrate if the router check does not pass

---

.github/workflows/coverage_comment.yaml
.github/workflows/tests.yaml
makefile
pyproject.toml
requirements/development.txt
requirements/pytest-in-nox.txt

This PR adds a new GitHub Workflow that uses the `coverage` package (from Pypi) to run reports on the testing coverage.
This code could be swapped for, or enhanced by, a [codecov subscription](https://about.codecov.io/) in future.

Workflow for tracking coverage

---

docs/usage/operations.rst
src/django_pg_migration_tools/operations.py
tests/django_pg_migration_tools/test_operations.py
tests/example_app/models.py

Adds a new Django migration operation class `SaferRemoveIndexConcurrently`. The name is self-explanatory, but here's a screenshot of the documentation (built with `make docs`) with more details (also available in the diff on the ante-penultimate commit).

SaferRemoveIndexConcurrently

---

CHANGELOG.md
pyproject.toml
requirements/development.txt
requirements/docs.txt
requirements/pytest-in-nox.txt

Prepare for release.
Merge after -> https://github.com/kraken-tech/django-pg-migration-tools/pull/18

Release safer remove index concurrently

---

docs/conf.py

This button should show up at the top-right on the Read The Docs template.
This fixes the problem with the current button showing "View page source" which displays the raw .rst file backing up the page.
tested via `make docs`

Add Edit On Github button

---

makefile

They are crowding the results.
**Before**:
```
Name                          Stmts   Miss Branch BrPart  Cover
------------------------------------------------------------
__init__.py                   0       0      0      0   100%
management/__init__.py        0       0      0      0   100%
commands/__init__.py          0       0      0      0   100%
*migrate_with_timeouts.py     25      0     10      0   100%
*operations.py                67      0      6      0   100%
*timeouts.py                  73      5     36      2    92%
------------------------------------------------------------
TOTAL                         165      5    52      2    96%
```
**After**:
```
Name                         Stmts   Miss Branch BrPart  Cover …
```

Skip coverage of __init__.py files

---

makefile

This is a better alternative to not running coverage against __init__.py files entirely. This could've been a problem if those files had code in it.

Use --skip-empty for coverage report

---

CHANGELOG.md
docs/usage/management_commands.rst
src/django_pg_migration_tools/management/commands/migrate_with_timeouts.py
tests/django_pg_migration_tools/management/commands/test_migrate_with_timeouts.py

This branch adds a retry mechanism for `migrate_with_timeouts`.
```bash
./manage.py migrate_with_timeouts \
--lock-timeout-in-ms=10000 \
--statement-timeout-in-ms=10000
```
```bash
./manage.py migrate_with_timeouts \
--lock-timeout-in-ms=10000 \
--lock-timeout-max-retries=3 \
--lock-timeout-retry-exp=2 \
--lock-timeout-retry-min-wait-in-ms=3000 \
--lock-timeout-retry-max-wait-in-ms=10000 \
--statement-timeout-in-ms=10000 \
--retry-callback--path="dotted.path.to.callback.function"
```

Add a retry mechanism for `migrate_with_timeouts`

---

makefile
tests/django_pg_migration_tools/test_timeouts.py

This will improve the coverage of the `apply_timeouts`, which is the only module we have with less than 100% coverage.
These changes add three scenarios that were acused by the coverage report of not being run:
1. A happy path when no timeout exceptions are raised.
2. When the inner code raises a transaction leak and we are allowed to
close the leaky transaction.
3. When the inner code raises a transaction leak and we are **NOT**
allowed to close the leaky transaction.

Improve coverage

---

CHANGELOG.md
src/django_pg_migration_tools/management/commands/migrate_with_timeouts.py
tests/django_pg_migration_tools/management/commands/test_migrate_with_timeouts.py
tests/example_app/settings.py

When we reach the maximum amount of retries we want to raise an specific exception type so that it doesn't get mixed with other CommandError's.

Use specific exc for too many retries

---

CHANGELOG.md
src/django_pg_migration_tools/management/commands/migrate_with_timeouts.py
tests/django_pg_migration_tools/management/commands/test_migrate_with_timeouts.py

The `migrate_with_timeouts` command can yield control to a callback every time a retry attempt happens.
Prior to this commit, the argument passed to the callback didn't include the stdout.
This prevented callbacks of handling the rich output that Django provides.
This particularly means that retry_callbacks can't understand which migration failed and is now being retried. In turn, the callback can't log or do anything about it.
With these changes, we pass the `io.StringIO` object that is an argument into the migrate command so that callbacks can use it as they wish.
The stdout will include an output like this:
Operations to perform:
Apply all migrations: ...
Running migrations:
Applying foo.0042_foo... OK
Applying bar.0777_bar...

Expose migration stdout to RetryState

---

CHANGELOG.md
docs/usage/operations.rst
src/django_pg_migration_tools/operations.py
tests/django_pg_migration_tools/test_operations.py

The main goal of this PR is to add an operation `SaferAddUniqueConstraint` that allows users to create a unique constraint on an existing table without downtime. The justification goes as follow:
The default operation used by Django (AddConstraint) performs a naive:
```sql
ALTER TABLE table ADD CONSTRAINT constraint UNIQUE (field);
```
This has several downsides:
- Blocks reads and writes.
- Can be blocked by other reads and writes and create a chain of locks.
- Doesn't work with retries (not idempotent).
This new class (`SaferAddUniqueConstraint`) provides a way to create a
unique constraint without locking reads/writes at all, by first creating
an UNIQUE index CONCURRENTLY, and using this index to generate the
constraint (which takes virtually no time) behind a lock-timeout.
Example …

Safer unique constraints

---

CHANGELOG.md
src/django_pg_migration_tools/management/commands/migrate_with_timeouts.py
tests/django_pg_migration_tools/management/commands/test_migrate_with_timeouts.py

It's useful to know how long a particular migration has been retrying for.
This commit will expose this information to the RetryState object that is passed to retry callbacks.
This will allow these callbacks to do interesting things such as logging how much time has elapsed since the migration started.

Add time since the migration started in RetryState

---

makefile

For new contributors installing their development environment via `make dev`, this will allow them to perform changes on the repo without reinstalling the package via `pip install .`.
This allows exploration, experimentation, and iterative changes to take place without having to repeat the pip install command too many times.
From the `pip install` man page:
```
-e, --editable <path/url>
Install a project in editable mode (i.e. setuptools "develop
mode") from a local project path or a VCS url.
(environment variable: PIP_EDITABLE)
```
This change addresses: https://github.com/kraken-tech/django-pg-migration-tools/issues/37

Install package in editable mode

---

CHANGELOG.md
docs/usage/operations.rst
src/django_pg_migration_tools/operations.py
tests/django_pg_migration_tools/test_operations.py
tests/example_app/models.py

The objective of this PR is to create a new operation called `SaferRemoveUniqueIndex` that provides the mirrored functionality of `SaferAddUniqueIndex`..
One could use Django's default `RemoveConstraint` operation which would perform the following DDL directly:
```sql
ALTER TABLE "table" DROP CONSTRAINT "constraint";
```
And the reverse DDL is:
```sql
ALTER TABLE "table" ADD CONSTRAINT "constraint" UNIQUE ("field");
```
However...
- Those operations are not idempotent.
- The reverse operation in particular is extra unsafe. It will block writes and reads.

Safer remove unique constraint

---

CHANGELOG.md
src/django_pg_migration_tools/operations.py
tests/django_pg_migration_tools/test_operations.py
tests/example_app/models.py

Postgres does not support unique constraints with conditions, however, Django allows it to be possible to specify a unique constraint with a condition. In postgres, these are represented as unique indexes with conditions instead
Here, we modify the operations to add or remove constraints to align with django operations behaviour - adding or removing the unique index - however with "if exists / not exists" and concurrently added to these.
An example of what is currently generated in Django when using a `migrations.AddConstraint(`
`CREATE UNIQUE INDEX "" ON "" ("") WHERE "status" IN (''ACCEPTED', 'GENERATED', 'STARTED');`

Handle scenario where unique constraint with condition is provided

---

CHANGELOG.md
src/django_pg_migration_tools/management/commands/migrate_with_timeouts.py
tests/django_pg_migration_tools/management/commands/test_migrate_with_timeouts.py

Users with multi-db Django configurations may want to know exactly which
database failed to push the migration forward.
This PR adds a new field called "database" to the RetryState dataclass so
that users who are hooking up onto the retry callback can find that
information.

Pass in database name to RetryState

---

docs/usage/operations.rst
src/django_pg_migration_tools/operations.py
tests/django_pg_migration_tools/management/commands/test_migrate_with_timeouts.py
tests/django_pg_migration_tools/test_operations.py
tests/example_app/models.py

When adding a new foreign key field, Django uses an AddField operation
with a ForeignKey field. This operation triggers the following DDLs:
```sql
ALTER TABLE "foo" ADD COLUMN "bar_id" bigint NULL
REFERENCES "bar" ("id") DEFERRABLE INITIALLY DEFERRED;
-- optional: if the field doesn't set index=False
CREATE INDEX "foo_bar_idx" ON "foo" ("bar_id");
```
There are two problems:
1. The ALTER TABLE command takes an AccessExclusive lock, which is the
highest level of locking. It will block reads and writes on both
tables.
2. The CREATE INDEX takes a Share lock which will conflict with inserts,
updates, and deletes on the table.
We want to achieve the same outcome as the above, but by performing DDLs
that block the database with locks that are as weak as possible, and for
the shortes time …

SaferAddFieldForeignKey operation

---

CHANGELOG.md
src/django_pg_migration_tools/operations.py
tests/django_pg_migration_tools/test_operations.py

Running django-pg-migration-tools version v0.1.11 against an existing
codebase, revealed the following problem:
```sh
./manage.py sqlmigrate myapp 0042
File "/lib/python3.12/site-packages/django/db/migrations/migration.py", line 132, in apply
operation.database_forwards(
File "/lib/python3.12/site-packages/django_pg_migration_tools/operations.py", line 1205, in database_forwards
ForeignKeyManager(
File "/lib/python3.12/site-packages/django_pg_migration_tools/operations.py", line 1016, in __init__
column_type: str | None = field.target_field.db_type(
^^^^^^^^^^^^^^^^^^
File "/lib/python3.12/site-packages/django/db/models/fields/related.py", line 1059, in target_field
return self.foreign_related_fields[0]
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File …
```

Bug fix safer fk operation

---

CHANGELOG.md
src/django_pg_migration_tools/operations.py

Django's schema_editor.execute command is special because when running sqlmigrate it only collects the SQL statements without running them.
This is different from getting a cursor and running the query against the database, which would immediately run the DDL no matter what.
This commit fixes so that all the DDLs are run through the schema_editor.
This commit does not include the instropection queries because that will be a more difficult fix. That is because the schema_editor.execute function does not return a cursor where we can call .fetchone or .fetchall. So if we can't fetch the result, we can answer the question from the instropection query.
There are way to override this behaviour with a few hacks, but since it is not immediately pressing this will have to come on a subsequent work …

Use schema_editor for executing DDLs

---

CHANGELOG.md
pyproject.toml
src/django_pg_migration_tools/operations.py
tests/django_pg_migration_tools/test_operations.py

Many of the introspection queries here break when the `sqlmigrate`
command runs without an up-to-date database schema.
For example, take this introspection query for checking if the column
already exists:
```sql
SELECT 1
FROM pg_catalog.pg_attribute
WHERE
attrelid = {table_name}::regclass
AND attname = {column_name};
```
If this introspection query run for real, in a database where the
{table_name} does not exist, it would return the following:
django.db.utils.ProgrammingError: relation "table_name" does not exist
LINE 5:     attrelid = 'table_name::regclass'
This happens because in certain cases the database doesn't have all
migrations applied and thus doesn't have a schema computed when the
sqlmigrate command runs.
This change adds a workaround, by not actually running the introspection …

Bug fix introspection queries for sqlmigrate

---

CHANGELOG.md
docs/usage/operations.rst
src/django_pg_migration_tools/operations.py
tests/django_pg_migration_tools/test_operations.py

Django CHECK constraints can be created in the following way:
```python
class Meta:
constraints = [
models.CheckConstraint(
check=Q(bar__gte=0),
name='bar_not_negative',
),
]
```
In this case, Django will create the following migration operations:
```python
operations = [
migrations.AddConstraint(
model_name='foo',
constraint=models.CheckConstraint(
check=Q(bar__gte=0),
name='bar_not_negative',
),
),
]
```
This operation will trigger an unsafe SQL query of the form:
```sql
ALTER TABLE foo
ADD CONSTRAINT bar_not_negative
CHECK (bar >= 0);
```
This operation acquires an AccessExclusiveLock, which is the most restricted
lock in Postgres, blocking any reads, writes, maintanence activities, and other
schema changes on the table.
It will also scan the whole table to make sure there are no …

Safer check constraints

---

.github/workflows/git.yaml

A fixup is included to prove the workflow works (by failing)

Add workflow to block fixup commits

---

CHANGELOG.md
src/django_pg_migration_tools/management/commands/migrate_with_timeouts.py
tests/django_pg_migration_tools/management/commands/test_migrate_with_timeouts.py
tests/example_app/settings.py

Prior to this change, the migrate_with_timeouts command could run in
parallel multiple times.
This is a problem because many migration operations that are multi-step
and non-atomic will behave badly under such circumstances.
To prevent this of happening, this command will now require a
session-level advisory lock for the entirety of its procedure.
The session-level advisory lock will be automatically removed once the
management command finishes, whether successfully or not.
See:
https://github.com/django/django/blob/857b1048/django/core/management/base.py#L426
Issue:
https://github.com/kraken-tech/django-pg-migration-tools/issues/59
The shell at the top ran the command with the following migration
<details>
Migration:
```py
from django.db import migrations
def sleep(*args, **kwargs): …
```

Run migrate_with_timeouts with an advisory lock

---

CHANGELOG.md
docs/index.rst
docs/usage/indexes.rst
docs/usage/operations.rst
src/django_pg_migration_tools/indexes.py
tests/django_pg_migration_tools/test_indexes.py

Django only supports unique constraints at the moment. There is no
support for unique indexes, specially partial unique indexes.
This PR adds a class that can be used in the Meta::indexes array.
Using the following models
```py
class IntModel(models.Model):
int_field = models.IntegerField()
class Meta:
indexes = [
indexes.UniqueIndex(
name="unique_int",
fields=["int_field"],
)
]
class CharModel(models.Model):
char_field = models.CharField(max_length=42)
class Meta:
indexes = [
indexes.UniqueIndex(
name="unique_char_unless_foo",
fields=["char_field"],
condition=~models.Q(char_field="foo")
)
]
```
Which creates the following default migration:
```
CREATE UNIQUE INDEX "unique_char_unless_foo" ON "blog_charmodel" ("char_field") WHERE NOT ("char_field" = 'foo');
CREATE UNIQUE INDEX …
```

Add unique index class

---

CONTRIBUTING.md
README.md

Prior to this change, the README.md file was looking rather empty. The only important information it contained was a link to the full documentation (ReadTheDocs page).
In some cases, potential users might come to the GitHub repository page directly and face a blank wall.
This commit adds a summary of the main features to the README.md with some click links for interested parties to navigate them.
https://github.com/kraken-tech/django-pg-migration-tools/tree/add-readme-main-features-section

Add a Main Features section in the README.md

---

CHANGELOG.md
docs/usage/operations.rst
src/django_pg_migration_tools/operations.py
tests/django_pg_migration_tools/test_operations.py

The default SQL DDL statements produced by Django to create a
OneToOneField are not safe to run and can cause outages.
For example, when the following foo field is added to Bar:
```py
class Bar(models.Model):
foo = models.OneToOneField(
Foo,
on_delete=models.CASCADE,
primary_key=False,  # False is the default
null=True,
)
```
A new migration is created via makemigrations with the following
operation:
```py
operations = [
migrations.AddField(
model_name='bar',
name='foo',
field=models.OneToOneField(
null=True,
on_delete=django.db.models.deletion.CASCADE,
to='blog.foo'
),
),
]
```
This operation, in turn, produces the following statements:
```sql
BEGIN;
--
-- Add field foo to bar
--
ALTER TABLE "blog_bar"
ADD COLUMN "foo_id" bigint NULL
UNIQUE CONSTRAINT "auto_gen_constraint_name" …
```

Safer Add Field OneToOne

---

CHANGELOG.md
docs/conf.py
docs/usage/operations.rst
pyproject.toml
requirements/development.txt
requirements/docs.txt
requirements/pytest-in-nox-psycopg2.txt
requirements/pytest-in-nox-psycopg3.txt
src/django_pg_migration_tools/operations.py
tests/django_pg_migration_tools/test_operations.py

Add support for `UniqueConstraint.deferrable`.
Here is a bare Django UniqueConstraint:
```py
class Foo(models.Model):
int_field = models.IntegerField(null=True)
class Meta:
constraints = [
UniqueConstraint(fields=['int_field'], name='unique_int_field'),
]
```
That generates the following SQL:
```sql
ALTER TABLE "blog_foo" ADD CONSTRAINT "unique_int_field" UNIQUE ("int_field");
```
So far so good. But Django allows a `deferrable` argument.
Accepted values are Deferrable.DEFERRED or Deferrable.IMMEDIATE. For example:
```py
from django.db.models import Deferrable, UniqueConstraint
UniqueConstraint(
fields=['int_field'],
name='unique_int_field',
deferrable=Deferrable.DEFERRED,
)
```
If Deferrable.DEFERRED, the migration output is:
```sql
ALTER TABLE "blog_foo" ADD CONSTRAINT …
```

Add deferrable to safer unique constraint

---

CHANGELOG.md
docs/usage/operations.rst
src/django_pg_migration_tools/operations.py
tests/django_pg_migration_tools/test_operations.py
tests/example_app/models.py

This is the analogous of `SaferAddFieldForeignKey` but does the opposite (-:

Safer remove field foreign key

---

CHANGELOG.md
README.md
docs/usage/operations.rst
src/django_pg_migration_tools/operations.py
tests/django_pg_migration_tools/test_operations.py
tests/example_app/models.py

Analogous to `SaferAddCheckConstraint` but does the reverse (-:

Safer remove check constraint

---

docs/usage/operations.rst

These DDL statements were missing the column name.

Fix syntax of CREATE INDEX CONCURRENTLY on docs

---

CHANGELOG.md
src/django_pg_migration_tools/operations.py
tests/django_pg_migration_tools/test_operations.py
tests/example_app/models.py

Changes:
Fix SaferAlterFieldSetNotNull for custom-named fields
Prior to this change, this operation didn't work for fields that had
column names in the database that didn't match their names (such as
ForeignKey fields, which have an "_id" suffix).
This commit changes that by obtaining the column name from the model's
meta class instead.

Fix safer alter field set not null for fk fields

---

docs/guides/migration_guides.rst
docs/index.rst
docs/usage/operations.rst

Much of our documentation is nested inside the "class definition" of each
operation.
The problem with that is that it is not obvious to a user coming to the repo
to know that there will be tutorials inside the class definition documentation.
This PR pulls out these tutorials/guides into a separated documentation page.
The content does not change, with the exception of a few adjustments when
necessary to fit the new `.rst` file structure and some double-linked links to
go from guide to class definition and vice-versa.
The new nav-bar looks like this:

Add documentation guides and background

---

CHANGELOG.md
src/django_pg_migration_tools/operations.py
tests/django_pg_migration_tools/test_operations.py
tests/example_app/models.py

Prior to this change, this operation didn't work for fields that referred to tables where the primary key field had a column name that differed from the field name.
This commit fixes that by referring to the column name instead of the field name.

Fix `SaferAddFieldForeignKey` when field name != column name

---

makefile
tests/django_pg_migration_tools/test_timeouts.py

This PR makes it so codecoverage also runs in the `tests/` folder.

Run coverage against test folder

---

CHANGELOG.md
src/django_pg_migration_tools/operations.py
tests/django_pg_migration_tools/test_operations.py

Change `collect_default` on constraint existing checks to require an explicit value rather than defaulting to false. This was causing the operation to say that the constraint did not exist and could not generate any SQL when the migration to drop a constraint was in collect only mode.
The value needs to be set to True when dropping constraints so that the SQL for what would happen if a constraint exists is shown (as the alternative is not useful).

Bugfix: drop unique constraint sqlmigrate is noop

---

CHANGELOG.md
src/django_pg_migration_tools/operations.py
tests/django_pg_migration_tools/test_operations.py
tests/example_app/models.py

This PR fixes a bug where a unique constraint with expressions produces invalid SQL when used with `SaferAddUniqueConstraint` and `SaferRemoveUniqueConstraint`.
These changes are based on a [previous PR](https://github.com/kraken-tech/django-pg-migration-tools/pull/42) which solved a similar issue for unique constraints with conditions.

Handle scenario where unique constraint with expression(s) is provided

---

CHANGELOG.md
docs/guides/migration_guides.rst
src/django_pg_migration_tools/operations.py
tests/django_pg_migration_tools/test_operations.py
tests/example_app/models.py

Prior to this change, if the FK field being removed had a null=False set up, this operation would fail:
ValueError: Can't safely create a FK field with null=False
While this error is relevant when the FK manager is *creating* a new column, it is not relevant when deleting one.
This commit changes that by skipping the nullability check when running from SaferRemoveFieldForeignKey.
A note was dropped on the documentation to alert that the field will be created with null=True when reversing the operation, since the alternative wouldn't be safe.

Fix SaferRemoveFieldForeignKey for non null columns
